services:
  nginx:
    image: nginx
    ports: 
      - "8081:80"
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    image: php:fpm-alpine
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    ports: 
      - "9000"